//! Build script: auto-discover stdlib .ns files for compile-time embedding.
//!
//! Scans the `stdlib/` directory recursively and generates a Rust source file
//! containing `include_str!()` entries for every `.ns` file found. This removes
//! the need to manually maintain the list in `src/stdlib.rs`.

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let stdlib_dir = Path::new(&manifest_dir).join("stdlib");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("stdlib_embedded.rs");

    let mut files = Vec::new();
    collect_ns_files(&stdlib_dir, &stdlib_dir, &mut files);
    files.sort();

    // Emit rerun-if-changed for each discovered file and directory so that
    // additions/removals in subdirectories (e.g. stdlib/primitives/) trigger rebuilds.
    println!("cargo:rerun-if-changed={}", stdlib_dir.display());
    for rel_path in &files {
        let full = stdlib_dir.join(rel_path);
        println!("cargo:rerun-if-changed={}", full.display());
    }

    let mut out = fs::File::create(&dest_path).unwrap();

    writeln!(out, "// Auto-generated by build.rs — do not edit").unwrap();
    writeln!(out, "&[").unwrap();

    for rel_path in &files {
        // Use forward slashes for the display name (consistent cross-platform)
        let display = rel_path.replace('\\', "/");
        writeln!(
            out,
            "    (\"{}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/stdlib/{}\"))),",
            display, display
        )
        .unwrap();
    }

    writeln!(out, "]").unwrap();
}

/// Recursively collect .ns files relative to the stdlib root.
fn collect_ns_files(dir: &Path, root: &Path, files: &mut Vec<String>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };

    for entry in entries.filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_dir() {
            collect_ns_files(&path, root, files);
        } else if path.extension().and_then(|s| s.to_str()) == Some("ns") {
            if let Ok(rel) = path.strip_prefix(root) {
                if let Some(s) = rel.to_str() {
                    files.push(s.to_string());
                }
            }
        }
    }
}
