/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'tutorials/shape-inference',
        'tutorials/fork-join',
        'tutorials/match-guards',
      ],
    },
    {
      type: 'category',
      label: 'Primitives',
      link: {
        type: 'doc',
        id: 'primitives/index',
      },
      items: [
        {
          type: 'category',
          label: 'Basics',
          items: [
            'primitives/Basics/linear',
          ],
        },
        {
          type: 'category',
          label: 'Activations',
          items: [
            'primitives/Activations/relu',
            'primitives/Activations/gelu',
            'primitives/Activations/silu',
            'primitives/Activations/sigmoid',
            'primitives/Activations/tanh',
            'primitives/Activations/softmax',
            'primitives/Activations/elu',
            'primitives/Activations/prelu',
            'primitives/Activations/mish',
          ],
        },
        {
          type: 'category',
          label: 'Convolutions',
          items: [
            'primitives/Convolutions/conv1d',
            'primitives/Convolutions/conv2d',
            'primitives/Convolutions/conv3d',
            'primitives/Convolutions/depthwiseconv',
            'primitives/Convolutions/separableconv',
            'primitives/Convolutions/transposedconv',
          ],
        },
        {
          type: 'category',
          label: 'Normalization',
          items: [
            'primitives/Normalization/batchnorm',
            'primitives/Normalization/layernorm',
            'primitives/Normalization/groupnorm',
            'primitives/Normalization/instancenorm',
            'primitives/Normalization/rmsnorm',
          ],
        },
        {
          type: 'category',
          label: 'Pooling',
          items: [
            'primitives/Pooling/maxpool',
            'primitives/Pooling/avgpool',
            'primitives/Pooling/globalavgpool',
            'primitives/Pooling/globalmaxpool',
            'primitives/Pooling/adaptiveavgpool',
            'primitives/Pooling/adaptivemaxpool',
          ],
        },
        {
          type: 'category',
          label: 'Attention',
          items: [
            'primitives/Attention/scaleddotproductattention',
            'primitives/Attention/multiheadselfattention',
          ],
        },
        {
          type: 'category',
          label: 'Embeddings',
          items: [
            'primitives/Embeddings/embedding',
            'primitives/Embeddings/positionalencoding',
            'primitives/Embeddings/learnedpositionalembedding',
            'primitives/Embeddings/rotaryembedding',
          ],
        },
        {
          type: 'category',
          label: 'Structural',
          items: [
            'primitives/Structural/fork',
            'primitives/Structural/fork3',
            'primitives/Structural/concat',
            'primitives/Structural/split',
            'primitives/Structural/add',
            'primitives/Structural/multiply',
            'primitives/Structural/reshape',
            'primitives/Structural/flatten',
            'primitives/Structural/transpose',
            'primitives/Structural/slice',
            'primitives/Structural/pad',
          ],
        },
        {
          type: 'category',
          label: 'Operations',
          items: [
            'primitives/Operations/matmul',
            'primitives/Operations/einsum',
            'primitives/Operations/bias',
            'primitives/Operations/scale',
            'primitives/Operations/identity',
          ],
        },
        {
          type: 'category',
          label: 'Regularization',
          items: [
            'primitives/Regularization/dropout',
            'primitives/Regularization/dropconnect',
            'primitives/Regularization/droppath',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Standard Library',
      link: {
        type: 'doc',
        id: 'stdlib/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stdlib',
        },
      ],
    },
    {
      type: 'category',
      label: 'Packages',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'packages/index',
      },
      items: [
        'packages/creating-packages',
        'packages/dependencies',
        'packages/publishing',
        'packages/cli-reference',
      ],
    },
  ],
};

export default sidebars;
