/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Primitives',
      link: {
        type: 'doc',
        id: 'primitives/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'primitives',
        },
      ],
    },
    {
      type: 'category',
      label: 'Standard Library',
      link: {
        type: 'doc',
        id: 'stdlib/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'stdlib',
        },
      ],
    },
  ],
};

export default sidebars;
